### ISSUE TITLE
JSON only update changed fields

### ISSUE THREAD

**Issue by agupta01** [rocketproplab/Base11-GUI#14]
Currently, the JSON gets rewritten every time data is fetched causing a super ugly flicker every 2 secs on the UI (the JSON file gets momentarily cleared, so the UI thinks this is an error, but then immediately comes back, causing the appearance of a flicker).
Avoid this flicker by only updating fields as necessary. Use .seek() and the fileIO tools instead of json package in python to do this.

Basic steps:
1. get most recent data (should already be implemented)
2. parse data
3. compare parsed data fields with fields from JSON (read JSON into local dictionary before this step)
4. if a field is different, seek through the JSON and change only that field

**Comment by longggle** [comment]
I'll take this
